# Makefile för macOS anpassad för ditt projekt
SRCDIR=./src
INCDIR=./include
CC=clang
CFLAGS = -g -c $(shell sdl2-config --cflags) -I$(INCDIR)
LDFLAGS = $(shell sdl2-config --libs) -lSDL2_image -lm -lSDL2_ttf -lSDL2_net

# Namnet på ditt mål (exekverbar fil)
TARGET = Football

# Objektfiler som ska byggas
OBJS = $(SRCDIR)/main.o $(SRCDIR)/controller.o $(SRCDIR)/model.o $(SRCDIR)/view.o $(SRCDIR)/network.o

# Standard byggregel
$(TARGET): $(OBJS)
	$(CC) -o $(TARGET) $(OBJS) $(LDFLAGS)

# Regel för att bygga .o filer från .c filer
$(SRCDIR)/%.o: $(SRCDIR)/%.c
	$(CC) $(CFLAGS) -o $@ -c $<

# Städa projektet från byggfiler och exekverbara filer
clean:
	rm -f $(SRCDIR)/*.o $(TARGET)
